tasks:
  - task: Pull latest code
    commands:
      - git reset --hard
      - git clean -fd
      - git pull origin main

  - task: Install dependencies
    commands:
      - npm install --production
      - npm install --include=dev

  - task: Build TypeScript
    commands:
      - npm run build

  - task: Restart Node app
    commands:
      - pm2 stop botify-backend || true
      - pm2 start dist/index.js --name botify-backend --env production